### ISSUE TITLE
Localization failed for CSV loader v2

### ISSUE THREAD

**Issue by Wilson13** [aissat/easy_localization#190]
Created new issue as old one was closed but not resolved.

Replies are referenced below.

> Version:
> 
> easy_localization: ^2.2.1
> easy_localization_loader: ^0.0.2
> Description:
> I encountered this error when using a CSV file to provide for localization.
> 
> Error:
> [easy_localization] Missing message : Not found this Key ["clickMe"]

> @Overman775 Thanks for noticing that, to simplify things, I removed the zh_Hans_SG_ entirely and kept only two locales, but the error persisted.

> langs.csv
> 
> ```
> str,en_SG,ms_SG
> clickMe,Test,Hallo
> title,what,Hallo
> Usage
> print('title'.tr());
> ```
> 
> Logs
> ```
> [Easy Localization] Start locale loaded ms_SG
> [log] easy localization loader: load csv file assets/langs/langs.csv
> [Easy Localization] Init Localization Delegate
> [Easy Localization] Init provider
> [MyApp # locale] ms_SG
> [Easy Localization] Load Localization Delegate
> I/flutter ( 4456): [WARNING] Easy Localization: Localization key [title] not found
> I/flutter ( 4456): title
> ```

https://github.com/aissat/easy_localization/issues/153#issuecomment-629930776

https://github.com/aissat/easy_localization/issues/153#issuecomment-629989562

**Comment by Maus3rSR** [comment]
I have also this problem with CSV loader but it occured only on iOS..
And I did not forget :
`	<key>CFBundleLocalizations</key>
	<array>
		<string>en</string>
		<string>fr</string>
	</array>`

The logs are exactly the same as @Wilson13 

I'm using
`Flutter 1.17.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (3 weeks ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1`

**Comment by Maus3rSR** [comment]
Ok got it..... It's because EOL default option is for CRLF files... My files are LF.

**Comment by Overman775** [comment]
@Maus3rSR Thanks for the help, I’ll fix it in my free time or you can do PR 😉

**Comment by Maus3rSR** [comment]
I'll see if I can do it, I'm not familiar with Dart architecture :-) Maybe next week I can do it.

**Comment by Overman775** [comment]
@Maus3rSR @Wilson13 
please check fix issue

1. edit pub
```
dependencies:
  easy_localization_loader:
    git:
      url: git://github.com/aissat/easy_localization_loader.git
      ref: overman-dev
```
2. run in terminal
` flutter pub upgrade`

**Comment by Overman775** [comment]
@aissat can you test new fixed in your mac? need delete file and create new csv file

**Comment by brenodt** [comment]
@Overman775 @aissat Shouldn't the loader package be updated with this fix? I think it would be helpful for newcomers, as the current official version found in pub.dev still presents this issue.

**Comment by Flutter-Butter** [comment]
I still encounter the same problem, this is my main:

import 'package:flutter/material.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:url_launcher/url_launcher_string.dart';
import 'config_route.dart';
import 'info_route.dart';
import 'updates_route.dart';
import 'radares.dart';
import 'idioma.dart';
import 'reseteo.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Future.delayed(const Duration(seconds: 1));
  await EasyLocalization.ensureInitialized();
  runApp(
    EasyLocalization(
      supportedLocales: const [
        Locale('en', 'UK'),
        Locale('ar', 'AR'),
        Locale('fr', 'FR'),
        Locale('es', 'ES')
      ],
      path: 'assets/lang/',
      fallbackLocale: const Locale('en'),
      startLocale: const Locale.fromSubtags(languageCode: 'en'),
      saveLocale: false,
      useOnlyLangCode: true,
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      localizationsDelegates: context.localizationDelegates,
      supportedLocales: context.supportedLocales,
      locale: context.locale,
      home: Builder(builder: (context) {
        return const ButtonPage();
      }),
    );
  }
}

class Language {
  Locale locale;
  String langName;
  Language({
    required this.locale,
    required this.langName,
  });
}

class ButtonPage extends StatefulWidget {
  const ButtonPage({super.key});

  @override
  ButtonPageState createState() => ButtonPageState();
}

class ButtonPageState extends State<ButtonPage> {
  bool isButtonPressed = false;
  bool isButtonPressed1 = false;
  List<Language> languageList = [
    Language(
      langName: 'English - UK',
      locale: const Locale('en'),
    ),
    Language(
      langName: 'Arabic - Ar',
      locale: const Locale('ar'),
    ),
    Language(
      langName: 'French - FR',
      locale: const Locale('fr'),
    ),
    Language(
      langName: 'Spanish - Es',
      locale: const Locale('es'),
    )
  ];

  Language? selectedLang;

  void toggleButton() {
    setState(() {
      isButtonPressed = !isButtonPressed;
      isButtonPressed1 = true;
    });
    Future.delayed(const Duration(milliseconds: 300), () {
      setState(() {
        isButtonPressed1 = false;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    selectedLang = languageList.singleWhere((e) => e.locale == context.locale);
    return Scaffold(
      appBar: AppBar(
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(20.0),
          child: Container(
            height: 40,
            padding: const EdgeInsets.only(left: 5),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(3),
              border: Border.all(color: Colors.black, width: .9),
            ),
            child: Container(
              padding: const EdgeInsets.only(left: 4, right: 4),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                mainAxisSize: MainAxisSize.min,
                children: <Widget>[
                  DropdownButton<Language>(
                    iconSize: 18,
                    elevation: 16,
                    value: selectedLang,
                    style: const TextStyle(color: Colors.black),
                    underline: Container(
                      padding: const EdgeInsets.only(left: 4, right: 4),
                      color: Colors.transparent,
                    ),
                    onChanged: (newValue) {
                      setState(() {
                        selectedLang = newValue!;
                      });
                      if (newValue!.langName == 'English - UK') {
                        context.setLocale(const Locale('en'));
                      } else if (newValue.langName == 'Arabic - Ar') {
                        context.setLocale(const Locale('ar'));
                      } else if (newValue.langName == 'French - FR') {
                        context.setLocale(const Locale('fr'));
                      } else if (newValue.langName == 'Spanish - Es') {
                        context.setLocale(const Locale('es'));
                      }
                    },
                    items: languageList.map<DropdownMenuItem<Language>>(
                      (Language value) {
                        return DropdownMenuItem<Language>(
                          value:
                              value, // Make sure this value is assigned correctly
                          child: Text(
                            value.langName,
                            style: const TextStyle(
                              fontSize: 12,
                              fontWeight: FontWeight.w600,
                              color: Colors.black,
                            ),
                          ),
                        );
                      },
                    ).toList(),
                  ),
                ],
              ),
            ),
          ),
        ),
        // ... other AppBar properties
      ),

      drawer: const SideMenu(), // Add the Drawer widget here
      body: Padding(
        padding: const EdgeInsets.fromLTRB(40.0, 20.0, 40.0, 0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Container(
              margin: const EdgeInsets.only(
                  bottom: 20.0), // Add margin to push content down
              child: Image.asset(
                'assets/images/closed.png',
                width: 300,
                height: 90,
              ),
            ),
            // InkWell(
            //   onTap: () {
            //     const url = 'https://www.masteringenieros.com/';
            //     launchUrlString(url);
            //   },
            //   child: const Text(
            //     'www.masteringenieros.com',
            //     style: TextStyle(
            //       color: Colors.blue, // Add a color to indicate it's a link
            //       decoration: TextDecoration.underline,
            //     ),
            //   ),
            // ),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Expanded(
                  child: ElevatedButton(
                    onPressed: () {},
                    style: ElevatedButton.styleFrom(
                      textStyle: const TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    child: Row(
                      // Use Row to add an icon and text
                      children: [
                        Image.asset(
                          'assets/images/auto.png',
                          width: 30,
                          height: 30,
                        ), // Replace 'Icons.auto' with the desired icon
                        const SizedBox(
                            width: 10), // Add some space between icon and text
                        Text("${"AUTO".tr()}:"),
                      ],
                    ),
                  ),
                ),
...
and this is the code in pubspec.yaml:
[pubspec_yaml.txt](https://github.com/aissat/easy_localization/files/12472064/pubspec_yaml.txt)

The error in debug console is:
I/flutter ( 5813): [🌎 Easy Localization] [DEBUG] Load asset from assets/lang
I/flutter ( 5813): Locale set to Spanish
I/flutter ( 5813): [🌎 Easy Localization] [INFO] Locale es changed
I/flutter ( 5813): [🌎 Easy Localization] [DEBUG] Build
I/flutter ( 5813): [🌎 Easy Localization] [DEBUG] Init Localization Delegate
I/flutter ( 5813): [🌎 Easy Localization] [DEBUG] Init provider
I/flutter ( 5813): [🌎 Easy Localization] [WARNING] Localization key [AUTO] not found
I/flutter ( 5813): [🌎 Easy Localization] [WARNING] Localization key [ABIERTO] not found
I/flutter ( 5813): [🌎 Easy Localization] [WARNING] Localization key [CERRADO] not found
I/flutter ( 5813): [🌎 Easy Localization] [WARNING] Localization key [SALIDA] not found
I/flutter ( 5813): [🌎 Easy Localization] [WARNING] Localization key [PARCIAL] not found
I/flutter ( 5813): [🌎 Easy Localization] [WARNING] Localization key [MANUAL] not found
I/flutter ( 5813): [🌎 Easy Localization] [WARNING] Localization key [INFORMACIÓN] not found
I/flutter ( 5813): [🌎 Easy Localization] [WARNING] Localization key [COMPROBAR ACTUALIZACIONES] not found
I/flutter ( 5813): [🌎 Easy Localization] [INFO] Locale es saved
D/EGL_emulation( 5813): app_time_stats: avg=26.29ms min=12.80ms max=367.57ms count=38
