### ISSUE TITLE
Black Screen is coming after splash screen.

### ISSUE THREAD

**Issue by siva563** [aissat/easy_localization#40]
Hi Team, 

Once added easy_localization into my project and used. It started getting a black screen after the splash screen.

Any fix for this issue.

**Comment by HugoHeneault** [comment]
Are you using the plugin in asset or remote mode?

**Comment by aissat** [comment]
#33

**Comment by sathya4code** [comment]
I am also facing the same issue. Any Solution...?

**Comment by aissat** [comment]
@sathya4code  try this [example](https://github.com/aissat/easy_localization/blob/master/example/lib/main.dart)

**Comment by sathya4code** [comment]
> @sathya4code try this [example](https://github.com/aissat/easy_localization/blob/master/example/lib/main.dart)

@aissat i tried this example. In this example also i am getting black screen. Default Splash Screen -> Black Screen -> Main Class.

**Comment by aissat** [comment]
@sathya4code which version you are used it?!!

**Comment by sathya4code** [comment]
> @sathya4code which version you are used it?!!

@aissat i am using easy_localization 1.3.3 and Flutter 1.12.13+hotfix.8

**Comment by madara134** [comment]
> > @sathya4code which version you are used it?!!
> 
> @aissat i am using easy_localization 1.3.3 and Flutter 1.12.13+hotfix.8

same issue

**Comment by aissat** [comment]
> > > @sathya4code which version you are used it?!!
> > 
> > 
> > @aissat i am using easy_localization 1.3.3 and Flutter 1.12.13+hotfix.8
> 
> same issue

@sathya4code i fixed  [your code](https://github.com/aissat/easy_localization/issues/40#issuecomment-585605133)
```dart
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() => runApp(EasyLocalization(
      child: MyApp(),
    ));

class MyApp extends StatelessWidget {
// This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    var data = EasyLocalizationProvider.of(context).data;
    return EasyLocalizationProvider(
      data: data,
      child: MaterialApp(
        localizationsDelegates: [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          EasyLocalizationDelegate(locale: data.locale, path: 'resources/langs')
        ],
        locale: data.locale,
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: MyHomePage(title: 'Flutter Demo Home Page'),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final title;
  MyHomePage({Key key, this.title}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    print(widget.title);
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
 
```

**Comment by sathya4code** [comment]
> > > > @sathya4code which version you are used it?!!
> > > 
> > > 
> > > @aissat i am using easy_localization 1.3.3 and Flutter 1.12.13+hotfix.8
> > 
> > 
> > same issue
> 
> @sathya4code i fixed [your code](https://github.com/aissat/easy_localization/issues/40#issuecomment-585605133)
> 
> ```dart
> import 'package:easy_localization/easy_localization.dart';
> import 'package:flutter/material.dart';
> import 'package:flutter_localizations/flutter_localizations.dart';
> 
> void main() => runApp(EasyLocalization(
>       child: MyApp(),
>     ));
> 
> class MyApp extends StatelessWidget {
> // This widget is the root of your application.
>   @override
>   Widget build(BuildContext context) {
>     var data = EasyLocalizationProvider.of(context).data;
>     return EasyLocalizationProvider(
>       data: data,
>       child: MaterialApp(
>         localizationsDelegates: [
>           GlobalMaterialLocalizations.delegate,
>           GlobalWidgetsLocalizations.delegate,
>           EasyLocalizationDelegate(locale: data.locale, path: 'resources/langs')
>         ],
>         locale: data.locale,
>         title: 'Flutter Demo',
>         theme: ThemeData(
>           primarySwatch: Colors.blue,
>         ),
>         home: MyHomePage(title: 'Flutter Demo Home Page'),
>       ),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   final title;
>   MyHomePage({Key key, this.title}) : super(key: key);
> 
>   @override
>   _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   int _counter = 0;
> 
>   void _incrementCounter() {
>     setState(() {
>       _counter++;
>     });
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     print(widget.title);
>     return Scaffold(
>       appBar: AppBar(
>         title: Text(widget.title),
>       ),
>       body: Center(
>         child: Column(
>           mainAxisAlignment: MainAxisAlignment.center,
>           children: [
>             Text(
>               'You have pushed the button this many times:',
>             ),
>             Text(
>               '$_counter',
>               style: Theme.of(context).textTheme.display1,
>             ),
>           ],
>         ),
>       ),
>       floatingActionButton: FloatingActionButton(
>         onPressed: _incrementCounter,
>         tooltip: 'Increment',
>         child: Icon(Icons.add),
>       ), // This trailing comma makes auto-formatting nicer for build methods.
>     );
>   }
> }
>  
> ```

@aissat Issue not fixed. Run this code, press the home button, open the app, black screen not coming. But killing the app and again opening the app makes black screen coming.. Can you please check this and give us a solution.

**Comment by aissat** [comment]
@sathya4code I tested code and worked well

**Comment by sathya4code** [comment]
> @sathya4code I tested code and worked well

I tested the same code with 1.3.5 version. Getting the same issue.

**Comment by aissat** [comment]
@sathya4code I need more details about this issue 
Debug and errors messages

**Comment by sathya4code** [comment]
> @sathya4code I need more details about this issue
> Debug and errors messages

@aissat  This is what i got when i debug,

`Launching lib\fixed_1.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
D/FlutterActivity(11018): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(11018): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(11018): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(11018): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView(11018): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@65730a2
D/FlutterActivityAndFragmentDelegate(11018): Executing Dart entrypoint: main, and sending initial route: /
D/EGL_emulation(11018): eglMakeCurrent: 0xdd9612c0: ver 3 1 (tinfo 0xd23cbc50)
Syncing files to device Android SDK built for x86...
I/OpenGLRenderer(11018): Davey! duration=854ms; Flags=1, IntendedVsync=526350506611692, Vsync=526350523278358, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=526350538945980, AnimationStart=526350538999180, PerformTraversalsStart=526350539038780, DrawStart=526351093237280, SyncQueued=526351094328980, SyncStart=526351275036680, IssueDrawCommandsStart=526351276141180, SwapBuffers=526351299175780, FrameCompleted=526351541456980, DequeueBufferDuration=225410000, QueueBufferDuration=2061000, 
I/Choreographer(11018): Skipped 60 frames!  The application may be doing too much work on its main thread.
D/FlutterView(10845): Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@a8f7c23
D/EGL_emulation(11018): eglMakeCurrent: 0xdd962460: ver 3 1 (tinfo 0xd23cbe40)
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
I/flutter (11018): Flutter Demo Home Page
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
I/flutter (11018): Flutter Demo Home Page
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): 
D/skia    (11018): Shader compilation error
D/skia    (11018): ------------------------
D/skia    (11018): Errors:
D/skia    (11018): `

**Comment by aissat** [comment]
@sathya4code this issues not from my package 
take a look here:
 [8578 Shader compilation error](https://github.com/flutter/flutter/issues/33018)
 [Shader compilation error (Skia)](https://github.com/flutter/flutter/issues/33019)
